version: 2
jobs:
  build:
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    steps:
        - checkout
        - run: cat /etc/os-release
        - run: npm -v
        - run: node -v
        - run: npm install -d
        - run: npm run build
        - run: node ./node_modules/aws-cdk/bin/cdk.js synth
        - setup_remote_docker:
            version: 18.06.0-ce
        - run: echo "y" |  node ./node_modules/aws-cdk/bin/cdk.js deploy  --require-approval=never